github: ["1-ManArmy"]                     # GitHub Sponsors (optional)
patreon: ["stingyguyus"]                # Patreon username (no URL)
custom: ["https://onelastai.com/contact"] # Custom donation or seva link
